name: Build LegendsBrowser

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build MacOS
      run: cd backend && GOOS=darwin GOARCH=amd64 go build -o ../bin/legendsbrowser-mac
    - name: Build Linux
      run: cd backend && GOOS=linux GOARCH=amd64 go build -o ../bin/legendsbrowser-linux-x64
    - name: Build Windows
      run: cd backend && GOOS=windows GOARCH=amd64 go build -o ../bin/legendsbrowser-win-x64.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          bin